In [0]:
import tensorflow as tf

In [3]:
x=tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(x)
print(x.shape)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)


In [4]:
y=tf.constant([[1.0,0.0],[0.0, 1.0], [1.0, 0.0], [0.0, 1.0]])
print(y)
print(y.shape)

tf.Tensor(
[[1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]], shape=(4, 2), dtype=float32)
(4, 2)


In [5]:
print(y.dtype)

<dtype: 'float32'>


In [6]:
a=tf.constant([1,2,3,4,5,6], shape=[2,3])
print(a)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [7]:
b=tf.constant([7,8,9,10,11,12], shape=[3,2])
print(b)

tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


In [8]:
c=tf.matmul(a,b)
print(c)

tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [9]:
j=tf.constant([1,2,3,4,5,6], shape=[2,3])
print(j)
k=tf.constant([7,8,9,10,11,12], shape=[2,3])
print(k)
l=tf.add(j,k)
print(l)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 8 10 12]
 [14 16 18]], shape=(2, 3), dtype=int32)
